name = "EikoNet"
__version__ = "1.0"
__description__ = "EikoNet: A deep neural networking approach for seismic ray tracing"
__license__ = "GPL v3.0"
__author__ = "Jonathan Smith, Kamyar Azizzadenesheli, Zachary E. Ross"
__email__ = "jdsmith@caltech.edu"